### ISSUE TITLE
DateTime deserializers truncate values for minute/second/millisecond.

### ISSUE THREAD

**Issue by Tukajo** [gkopff/gson-jodatime-serialisers#30]
I believe the reason this happens is because the default "Type" for a DateTime object only goes down to the hour.

I posted a bit on SO about it here:
http://stackoverflow.com/questions/31710000/joda-datetime-deserializer-is-truncating-datetimes-minute-second-millisecond

also a relevant post that may be able to help us fix this is here:
http://stackoverflow.com/questions/18786243/use-gson-with-date4j-datetime

**Comment by gkopff** [comment]
Ok cool. Thanks.  Are you likely to supply a pull request for this fix?

**Comment by Tukajo** [comment]
According to a reply on the first SO post. It may not even need a fix, just some annotation about JSON Formatting....

**Comment by gkopff** [comment]
I'll take a closer look then :)

**Comment by sgrossberndt** [comment]
This issue can be closed as it was fixed in 1.3.0 by https://github.com/gkopff/gson-jodatime-serialisers/commit/670e7c453611605462e0c61d849982cf5f1c94de#diff-18b4e8d45bdc0d29034024b99aba1124
