### ISSUE TITLE
DateTimeConverter crashes on parsing dates that have no millisecond value

### ISSUE THREAD

**Issue by Hikaru755** [gkopff/gson-jodatime-serialisers#34]
When parsing a string like `"2016-06-29T12:00:00+02:00"` the DateTimeConverter will crash, because it uses `ISODateTimeFormat.dateTime()` to get a formatter that explicitely expects a millisecond value. There is an alternative that explicitely doesn't excpect a millisecond value: `ISODateTimeFormat.dateTimeNoMillis()`.
Both versions should be supported, as both are quite common (and valid regarding ISO 8601).

**Comment by gkopff** [comment]
Thanks.  Are you able to supply the PR?

**Comment by Hikaru755** [comment]
@gkopff I think so, yeah. Any requirements, regarding code style, unit test, anything else from your part?

**Comment by gkopff** [comment]
Just match the existing style (2 space indentation, brace position etc), and include appropriate tests please.

**Comment by Hikaru755** [comment]
@gkopff Thanks for merging! Can you give an estimate when an update for the library will be available through maven?

**Comment by gkopff** [comment]
It's Friday night here, so I probably won't get around to the mechanics of releasing until Monday.  I'll post a note here once I've published it.

**Comment by Hikaru755** [comment]
Much appreciated, thanks!

**Comment by gkopff** [comment]
That's been published to Maven Central as `1.3.0`.
