### ISSUE TITLE
What is the expected release date for version 1.4

### ISSUE THREAD

**Issue by kangpengjie** [gkopff/gson-jodatime-serialisers#37]
I see you add PeriodConverter code, So What is the expected release date for version 1.4

**Comment by gkopff** [comment]
I got bust and didn't get to release it.  Did you however have a pull request that fixes #38 that could be included in 1.4?

**Comment by gkopff** [comment]
Released today.

**Comment by kangpengjie** [comment]
OK,Thanks!
