### ISSUE TITLE
Crashes on JsonNull object

### ISSUE THREAD

**Issue by lemberh** [gkopff/gson-jodatime-serialisers#41]
Throws exception here:
java.lang.UnsupportedOperationException: JsonObject at com.google.gson.JsonElement.getAsString
`// Do not try to deserialize null or empty values

        if json.getAsString() == null || json.getAsString().isEmpty()) {
            return null;
}`
it is because json.getAsString() throws it but json.toString() works good
here is stackoverflow question [https://stackoverflow.com/a/9324906/1307690](url)

**Comment by gkopff** [comment]
https://stackoverflow.com/a/9324906/1212960

**Comment by lemberh** [comment]
That was my mistake, I tried to deserialize data that was serialized there by default Gson serializer with gson-jodatime-serialisers and instead of JsonObject there was a JsonArray
